sudo: required
language: generic
services: docker
before_install:
 - docker pull aergus/latex
script:
 - docker run -t -v $TRAVIS_BUILD_DIR:/doc/ -w /doc aergus/latex /bin/sh -c "pdflatex -shell-escape -synctex=1 -interaction=nonstopmode --jobname=linux_shell_$TRAVIS_BRANCH main.tex"
 - docker run -t -v $TRAVIS_BUILD_DIR:/doc/ -w /doc aergus/latex /bin/sh -c "pdflatex -shell-escape -synctex=1 -interaction=nonstopmode --jobname=linux_shell_$TRAVIS_BRANCH main.tex"
deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  file: "linux_shell_$TRAVIS_BRANCH.pdf"
  skip_cleanup: true
  on:
    tags: true
